---

- name: Install locales
  ansible.builtin.apt:
    name: locales
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Create locales
  community.general.locale_gen.locale_gen:
    name: "{{ locale }}"
    state: present
  become: true

- name: Update-locale
  ansible.builtin.command: update-locale LC_ALL={{ locale }} LANG={{ locale }}
  changed_when: false
  become: true
