---

- name: Install locales
  ansible.builtin.apt:
    name: locales
    state: present
    update_cache: "{{ reset_locale_apt_update_cache | default(true) | bool }}"
    cache_valid_time: "{% if reset_locale_apt_update_cache | default(true) | bool %}3600{% else %}0{% endif %}"
  become: true

- name: Create locales
  community.general.locale_gen.locale_gen:
    name: "{{ locale }}"
    state: present
  become: true

- name: Update-locale
  ansible.builtin.command: update-locale LC_ALL={{ locale }} LANG={{ locale }}
  changed_when: false
  become: true
