---

- name: Stop accepting locale env vars from your client to the server
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^AcceptEnv LANG LC_(.+)"
    line: "#AcceptEnv LANG LC_\\1"
    backrefs: true
  become: true
  notify: Reload_ssh
